// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.6.1.0
//      SpecFlow Generator Version:1.6.0.0
//      Runtime Version:4.0.30319.235
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace Restbucks.ShoppingCart
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.6.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Change order location")]
    public partial class ChangeOrderLocationFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "ChangeOrderLocation.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Change order location", "In order to make it to work on time\r\nAs a coffee addict\r\nI want to change my coff" +
                    "ee order to go", GenerationTargetLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Change order location")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void ChangeOrderLocation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Change order location", new string[] {
                        "domain"});
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
 testRunner.Given("the franchise owner has set up the menu");
#line 9
 testRunner.And("I have created a cart");
#line 10
 testRunner.And("I have added a medium cappuccino, skim milk, single shot");
#line 11
 testRunner.And("I have placed the order \"for here\"");
#line 12
 testRunner.When("I change the order location to take away");
#line 13
 testRunner.Then("the order location is changed from in shop to take away");
#line 14
 testRunner.And("nothing else happens");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Can\'t change location on an unplaced order")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void CanTChangeLocationOnAnUnplacedOrder()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Can\'t change location on an unplaced order", new string[] {
                        "domain"});
#line 17
this.ScenarioSetup(scenarioInfo);
#line 18
 testRunner.Given("the franchise owner has set up the menu");
#line 19
 testRunner.And("I have created a cart");
#line 20
 testRunner.And("I have added a medium cappuccino, skim milk, single shot");
#line 21
 testRunner.When("I change the order location to take away");
#line 22
 testRunner.Then("the aggregate state is invalid");
#line 23
 testRunner.And("the error is \"You can\'t change the location before you place the order.\"");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Changing location to the same location does nothing")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void ChangingLocationToTheSameLocationDoesNothing()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Changing location to the same location does nothing", new string[] {
                        "domain"});
#line 26
this.ScenarioSetup(scenarioInfo);
#line 27
 testRunner.Given("the franchise owner has set up the menu");
#line 28
 testRunner.And("I have created a cart");
#line 29
 testRunner.And("I have added a medium cappuccino, skim milk, single shot");
#line 30
 testRunner.And("I have placed the order \"for here\"");
#line 31
 testRunner.When("I change the order location to in shop");
#line 32
 testRunner.Then("nothing happens");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Change location of a paid order")]
        [NUnit.Framework.CategoryAttribute("domain")]
        public virtual void ChangeLocationOfAPaidOrder()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Change location of a paid order", new string[] {
                        "domain"});
#line 35
this.ScenarioSetup(scenarioInfo);
#line 36
 testRunner.Given("the franchise owner has set up the menu");
#line 37
 testRunner.And("I have created a cart");
#line 38
 testRunner.And("I have added a medium cappuccino, skim milk, single shot");
#line 39
 testRunner.And("I have placed the order \"for here\"");
#line 40
 testRunner.And("I have paid for the order");
#line 41
 testRunner.When("I change the order location to take away");
#line 42
 testRunner.Then("the order location is changed from in shop to take away");
#line 43
 testRunner.And("nothing else happens");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
